name: freezed_weather
description: A rewrite of Flutter Weather Tutorial using freezed code generation.
publish_to: 'none' 
version: 2.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  weather_repository: 
    path: packages/weather_repository
  flutter_bloc: ^8.0.1
  hydrated_bloc: ^9.0.0-dev.2
  google_fonts: ^2.3.2
  path_provider: ^2.0.10
  bloc: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  freezed: ^2.0.3+1
  build_runner: ^2.1.10
  json_serializable: ^6.2.0
  bloc_test: ^9.0.3
  mocktail: ^0.3.0
  test: ^1.21.1

flutter:
  uses-material-design: true
